I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 114, in script call
    call research_game
  File "game/script.rpy", line 62, in script
    $ buttons_values = [img1]
  File "game/script.rpy", line 62, in <module>
    $ buttons_values = [img1]
NameError: name 'img1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 114, in script call
    call research_game
  File "game/script.rpy", line 62, in script
    $ buttons_values = [img1]
  File "C:\Users\Emily Jonatan\Downloads\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Emily Jonatan\Downloads\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 62, in <module>
    $ buttons_values = [img1]
NameError: name 'img1' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
You Are the Bad Guy 1.0
Sat Apr 18 16:15:15 2020
